#!/usr/bin/env bash
# update-steering-references.sh
#
# Reads frontmatter (name, description) from steering files:
#   - steering/eks.md (hub)
#   - steering/workflows/*.md (workflows)
#   - steering/commands/**/*.md (slash commands)
#
# Rebuilds the Steering Reference table in README.md between
# <!-- STEERING_REFERENCE_START --> and <!-- STEERING_REFERENCE_END --> markers.
#
# Usage:
#   ./misc/update-steering-references.sh          # run from repo root
#   ./misc/update-steering-references.sh --dry-run # preview without writing

set -euo pipefail
# Command substitutions must inherit errexit so a parse_frontmatter failure
# (exit 2 on invalid YAML) inside $(build_table) aborts before README.md is
# rewritten.
shopt -s inherit_errexit

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

python3 -c 'import yaml' 2>/dev/null || {
  echo "ERROR: PyYAML is required (pip install pyyaml)" >&2
  exit 1
}

README="$REPO_ROOT/README.md"
STEERING_DIR="$REPO_ROOT/steering"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

# --- Parse frontmatter from a markdown file ---
parse_frontmatter() {
  local file="$1"
  local key="$2"
  python3 - "$file" "$key" <<'PY'
import sys, yaml
path, key = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
except (OSError, UnicodeDecodeError) as e:
    print(f"ERROR: {path}: {e}", file=sys.stderr)
    sys.exit(2)
if not lines or lines[0].rstrip() != "---":
    sys.exit(0)
fm = []
for line in lines[1:]:
    if line.rstrip() == "---":
        break
    fm.append(line)
else:
    print(f"ERROR: {path}: unclosed frontmatter block (missing closing '---')", file=sys.stderr)
    sys.exit(2)
if len("".join(fm).encode("utf-8")) > 64 * 1024:
    print(f"ERROR: {path}: frontmatter block too large to parse", file=sys.stderr)
    sys.exit(2)
try:
    data = yaml.safe_load("".join(fm))
except yaml.YAMLError as e:
    print(f"ERROR: {path}: {e}", file=sys.stderr)
    sys.exit(2)
if not isinstance(data, dict):
    sys.exit(0)
val = data.get(key)
if val is None:
    sys.exit(0)
print(" ".join(str(val).split()))
PY
}

# --- Pick column count based on item count ---
_pick_cols() {
  local count="$1"
  if [ "$count" -le 4 ]; then
    echo "$count"
  elif [ "$count" -le 9 ]; then
    echo 3
  else
    echo 4
  fi
}

# --- Emit a grid table from a list of "[name](path)" items ---
_emit_grid() {
  local cols="$1"
  shift
  local items=("$@")

  echo '<table>'
  local col=0
  for item in "${items[@]}"; do
    if [ "$col" -eq 0 ]; then
      echo -n '<tr>'
    fi
    # item is like "[name](path)" - convert to HTML
    local name path
    name="$(echo "$item" | sed 's/\[//;s/\](.*)//')"
    path="$(echo "$item" | sed 's/.*](\(.*\))/\1/')"
    echo -n "<td><a href=\"${path}\"><b>${name}</b></a></td>"
    col=$((col + 1))
    if [ "$col" -eq "$cols" ]; then
      echo '</tr>'
      col=0
    fi
  done
  if [ "$col" -gt 0 ]; then
    while [ "$col" -lt "$cols" ]; do
      echo -n '<td></td>'
      col=$((col + 1))
    done
    echo '</tr>'
  fi
  echo '</table>'
}

# --- Build the Steering Reference table ---
build_table() {
  echo '## Steering'
  echo ''
  echo '> _This table is auto-generated by [`misc/update-steering-references.sh`](misc/update-steering-references.sh). Do not edit manually._'

  # Collect hub + workflow names
  local -a steering_items=()

  while IFS= read -r -d '' hub; do
    if [[ -f "$hub" ]]; then
      local name
      name="$(parse_frontmatter "$hub" "name")"
      [[ -n "$name" ]] || continue
      local rel_path="${hub#$REPO_ROOT/}"
      steering_items+=("[$name]($rel_path)")
    fi
  done < <(find "$STEERING_DIR" -maxdepth 1 -type f -name '*.md' -print0 | sort -z)

  if [[ -d "$STEERING_DIR/workflows" ]]; then
    for wf in "$STEERING_DIR/workflows"/*.md; do
      if [[ -f "$wf" ]]; then
        local name
        name="$(parse_frontmatter "$wf" "name")"
        [[ -n "$name" ]] || continue
        local rel_path="${wf#$REPO_ROOT/}"
        steering_items+=("[$name]($rel_path)")
      fi
    done
  fi

  echo ''
  echo '### Workflows'
  echo ''
  local count=${#steering_items[@]}
  _emit_grid "$(_pick_cols "$count")" "${steering_items[@]}"

  # Collect slash commands
  local -a cmd_items=()
  if [[ -d "$STEERING_DIR/commands" ]]; then
    while IFS= read -r -d '' cmd; do
      local cmd_name
      cmd_name="$(parse_frontmatter "$cmd" "name")"
      [[ -n "$cmd_name" ]] || continue
      local cmd_rel_path="${cmd#$REPO_ROOT/}"
      cmd_items+=("[/$cmd_name]($cmd_rel_path)")
    done < <(find "$STEERING_DIR/commands" -name '*.md' -print0 | sort -z)
  fi

  if [[ ${#cmd_items[@]} -gt 0 ]]; then
    echo ''
    echo '### Slash Commands'
    echo ''
    local cmd_count=${#cmd_items[@]}
    _emit_grid "$(_pick_cols "$cmd_count")" "${cmd_items[@]}"
  fi
}

# --- Replace the section in README.md ---
START_MARKER='<!-- STEERING_REFERENCE_START -->'
END_MARKER='<!-- STEERING_REFERENCE_END -->'

if ! grep -q "$START_MARKER" "$README"; then
  echo "ERROR: Could not find $START_MARKER in $README" >&2
  echo "Add the markers around the Steering section first." >&2
  exit 1
fi

if ! grep -q "$END_MARKER" "$README"; then
  echo "ERROR: Could not find $END_MARKER in $README" >&2
  exit 1
fi

# Build the new content
NEW_SECTION="$(build_table)"

if $DRY_RUN; then
  echo "=== DRY RUN — would replace Steering Reference with: ==="
  echo ""
  echo "$START_MARKER"
  echo "$NEW_SECTION"
  echo "$END_MARKER"
  echo ""
  echo "=== No changes written ==="
  exit 0
fi

# Use awk to replace everything between the markers (inclusive)
awk -v start="$START_MARKER" -v end="$END_MARKER" -v new_section="$NEW_SECTION" '
  $0 == start {
    print start
    print new_section
    skip = 1
    next
  }
  $0 == end {
    print end
    skip = 0
    next
  }
  !skip { print }
' "$README" > "$README.tmp"

mv "$README.tmp" "$README"

echo "✅ Steering Reference table updated in README.md"
echo "   Steering files found:"
while IFS= read -r -d '' f; do
  if [[ -f "$f" ]]; then
    local_name="$(parse_frontmatter "$f" "name")"
    if [[ -n "$local_name" ]]; then
      echo "   - $local_name (${f#$REPO_ROOT/})"
    fi
  fi
done < <(find "$STEERING_DIR" -maxdepth 1 -type f -name '*.md' -print0 | sort -z)
for f in "$STEERING_DIR/workflows"/*.md; do
  if [[ -f "$f" ]]; then
    local_name="$(parse_frontmatter "$f" "name")"
    if [[ -n "$local_name" ]]; then
      echo "   - $local_name (${f#$REPO_ROOT/})"
    fi
  fi
done
if [[ -d "$STEERING_DIR/commands" ]]; then
  echo "   Command files found:"
  while IFS= read -r -d '' f; do
    local_name="$(parse_frontmatter "$f" "name")"
    if [[ -n "$local_name" ]]; then
      echo "   - /$local_name (${f#$REPO_ROOT/})"
    fi
  done < <(find "$STEERING_DIR/commands" -name '*.md' -print0 | sort -z)
fi
