#!/usr/bin/env bash
# update-devops-agent-references.sh
#
# Reads SKILL.md frontmatter (name, description) from every skill in devops-agent/
# and rebuilds the DevOps Agent reference table in devops-agent/README.md
# (between DEVOPS_AGENT_REFERENCE markers).
#
# Usage:
#   ./misc/update-devops-agent-references.sh          # run from repo root
#   ./misc/update-devops-agent-references.sh --check  # fail if block is stale
#   ./misc/update-devops-agent-references.sh --dry-run # preview without writing

set -euo pipefail
# Command substitutions must inherit errexit so a parse_frontmatter failure
# (exit 2 on invalid YAML) inside $(build_table) aborts before README.md is
# rewritten.
shopt -s inherit_errexit

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

python3 -c 'import yaml' 2>/dev/null || {
  echo "ERROR: PyYAML is required (pip install pyyaml)" >&2
  exit 1
}

DEVOPS_README="$REPO_ROOT/devops-agent/README.md"
DEVOPS_DIR="$REPO_ROOT/devops-agent"
DRY_RUN=false
CHECK=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
elif [[ "${1:-}" == "--check" ]]; then
  CHECK=true
fi

# --- Parse frontmatter from a SKILL.md file ---
# Extracts the value for a given key from YAML frontmatter (between --- delimiters)
parse_frontmatter() {
  local file="$1"
  local key="$2"
  python3 - "$file" "$key" <<'PY'
import sys, yaml
path, key = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
except (OSError, UnicodeDecodeError) as e:
    print(f"ERROR: {path}: {e}", file=sys.stderr)
    sys.exit(2)
if not lines or lines[0].rstrip() != "---":
    sys.exit(0)
fm = []
for line in lines[1:]:
    if line.rstrip() == "---":
        break
    fm.append(line)
else:
    print(f"ERROR: {path}: unclosed frontmatter block (missing closing '---')", file=sys.stderr)
    sys.exit(2)
try:
    data = yaml.safe_load("".join(fm))
except yaml.YAMLError as e:
    print(f"ERROR: {path}: {e}", file=sys.stderr)
    sys.exit(2)
if not isinstance(data, dict):
    sys.exit(0)
val = data.get(key)
if val is None:
    sys.exit(0)
print(" ".join(str(val).split()))
PY
}

# --- Determine skill status ---
# "Active" if the skill has a references/ directory, otherwise "Placeholder"
get_skill_status() {
  local skill_dir="$1"
  if [[ -d "$skill_dir/references" ]]; then
    echo "Active"
  else
    echo "Placeholder"
  fi
}

# --- Build the devops-agent reference table ---
build_table() {
  echo '> _This table is auto-generated by [`misc/update-devops-agent-references.sh`](../misc/update-devops-agent-references.sh). Do not edit manually._'
  echo ''
  echo '| Skill | Status | Description |'
  echo '|-------|--------|-------------|'

  for skill_dir in "$DEVOPS_DIR"/*/; do
    local skill_md="$skill_dir/SKILL.md"
    if [[ ! -f "$skill_md" ]]; then
      continue
    fi

    local name
    name="$(parse_frontmatter "$skill_md" "name")"
    if [[ -z "$name" ]]; then
      echo "  WARNING: No name found in $skill_md" >&2
      continue
    fi

    local description
    description="$(parse_frontmatter "$skill_md" "description")"
    if [[ -z "$description" ]]; then
      description="_(no description in frontmatter)_"
    fi

    # Truncate long descriptions for table readability
    if [[ ${#description} -gt 200 ]]; then
      description="${description:0:197}..."
    fi

    local status
    status="$(get_skill_status "$skill_dir")"

    local folder_name
    folder_name="$(basename "$skill_dir")"

    echo "| [$name](./$folder_name/) | $status | $description |"
  done
}

# --- Replace a section between markers in a file ---
replace_section() {
  local file="$1"
  local start_marker="$2"
  local end_marker="$3"
  local new_content="$4"

  if ! grep -q "$start_marker" "$file"; then
    echo "ERROR: Could not find $start_marker in $file" >&2
    return 1
  fi

  if ! grep -q "$end_marker" "$file"; then
    echo "ERROR: Could not find $end_marker in $file" >&2
    return 1
  fi

  awk -v start="$start_marker" -v end="$end_marker" -v new_section="$new_content" '
    $0 == start {
      print start
      print new_section
      skip = 1
      next
    }
    $0 == end {
      print end
      skip = 0
      next
    }
    !skip { print }
  ' "$file" > "$file.tmp"

  mv "$file.tmp" "$file"
}

# =============================================
# Build the table content
# =============================================

START_MARKER='<!-- DEVOPS_AGENT_REFERENCE_START -->'
END_MARKER='<!-- DEVOPS_AGENT_REFERENCE_END -->'

if ! grep -q "$START_MARKER" "$DEVOPS_README"; then
  echo "ERROR: Could not find $START_MARKER in $DEVOPS_README" >&2
  echo "Add the markers around the DevOps Agent reference section first." >&2
  exit 1
fi

NEW_SECTION="$(build_table)"

if $DRY_RUN; then
  echo "=== DRY RUN — devops-agent/README.md Reference Table ==="
  echo ""
  echo "$START_MARKER"
  echo "$NEW_SECTION"
  echo "$END_MARKER"
  echo ""
  echo "=== No changes written ==="
  exit 0
fi

# =============================================
# Apply changes
# =============================================

replace_section "$DEVOPS_README" "$START_MARKER" "$END_MARKER" "$NEW_SECTION"
echo "  Updated devops-agent/README.md"

# --check mode: verify no diff
if $CHECK; then
  if ! git diff --quiet -- "$DEVOPS_README"; then
    echo ""
    echo "ERROR: devops-agent reference block is stale. Diff:"
    git --no-pager diff -- "$DEVOPS_README"
    echo ""
    echo "Fix: run ./misc/update-devops-agent-references.sh locally, commit the result."
    exit 1
  fi
  echo "  devops-agent/README.md is in sync"
fi
